#!/usr/bin/bash
set -euo pipefail

git submodule update --init --recursive
git submodule update 

export PREFIX=${CONDA_PREFIX}
export WORKDIR=${PWD}
export CABANASRC=${CONDA_PREFIX}/cabana
export KOKKOSSRC=${CONDA_PREFIX}/kokkos

conda env config vars set PREFIX=${PREFIX} WORKDIR=${WORKDIR} CPATH=${PREFIX}/include CABANASRC=${CABANASRC} KOKKOSSRC=${KOKKOSSRC}



cd ${PREFIX}

git clone https://gitlab.cern.ch/hepmc/HepMC3.git
cd HepMC3
git checkout 7c7f4e5b1ffa5702787ca6c40ccc26f356bedb75
cd ..
mkdir hepmc3-build          
cd hepmc3-build

cmake -DHEPMC3_ENABLE_ROOTIO=ON -DROOT_DIR=${ROOTSYS} -DCMAKE_INSTALL_PREFIX=$PREFIX ../HepMC3
make -j8 install

cd $PREFIX

wget https://pythia.org/download/pythia83/pythia8310.tgz
tar xf pythia8310.tgz && rm pythia8310.tgz
cd pythia8310
./configure --prefix=${PREFIX} --with-hepmc3=${PREFIX}/HepMC3 --cxx-common='-std=c++17 -march=native -O3 -fPIC -pthread'
make -j8 install

git clone https://github.com/kokkos/kokkos.git $KOKKOSSRC
cd $KOKKOSSRC
git checkout 4.1.00
mkdir -p $KOKKOSSRC/build && cd $KOKKOSSRC/build

cmake -DCMAKE_BUILD_TYPE="Release" \
      -DCMAKE_INSTALL_PREFIX=$PREFIX \
      -DCMAKE_CXX_COMPILER=g++ \
      -DCMAKE_CXX_STANDARD=17 \
      -DCMAKE_CXX_EXTENSIONS=Off \
      -DKokkos_ENABLE_COMPILER_WARNINGS=ON \
      -DKokkos_ENABLE_CUDA=Off \
      -DKokkos_ENABLE_CUDA_LAMBDA=Off \
      -DKokkos_ENABLE_OPENMP=On \
      -DKokkos_ENABLE_SERIAL=On \
      -DKokkos_ENABLE_TESTS=Off \
      -DKokkos_ARCH_AMPERE80=Off $KOKKOSSRC
cmake --build . --target install -j

git clone https://github.com/ECP-copa/Cabana.git $CABANASRC
cd $CABANASRC
git checkout 8cf259913e8fb3822ce5095f6349c56798190471
mkdir -p $CABANASRC/build && cd $CABANASRC/build
    cmake -D CMAKE_BUILD_TYPE="Release" \
          -D CMAKE_CXX_STANDARD=17 \
          -D CMAKE_PREFIX_PATH=$CABANASRC \
          -D CMAKE_INSTALL_PREFIX=$PREFIX \
          -D CMAKE_CXX_COMPILER=g++\
          -D Cabana_REQUIRE_CUDA=OFF \
          -D Cabana_ENABLE_TESTING=OFF \
          -D Cabana_ENABLE_EXAMPLES=OFF $CABANASRC
cmake --build . --target install -j




export EIGEN3_ROOT="${PREFIX}/eigen3"          
export PYTHIA8DIR="${PREFIX}/pythia8310"
export PYTHIA8_ROOT_DIR="${PREFIX}/pythia8310"
export HEPMC_DIR=${PREFIX}




cd $WORKDIR/models/trento
mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=$PREFIX
make -j8 install

cd $WORKDIR/models/CCAKE

mkdir -p EoS/Houston && \
wget -O EoS/Houston/thermo.dat https://zenodo.org/record/6829115/files/thermo.dat?download=1 && \
wget -O EoS/Houston/thermo.h5 https://zenodo.org/record/6829115/files/thermo.h5?download=1

mkdir build && cd build
cmake ..
make -j8


cd $WORKDIR/models/iS3D
mkdir build && cd build
cmake ..
make -j8 install


#5) Setup environment variables
export SMASH_DIR="${WORKDIR}/models/smash/"

conda env config vars set SMASH_DIR=${SMASH_DIR} EIGEN3_ROOT=${EIGEN3_ROOT} PYTHIA8DIR=${PYTHIA8DIR} PYTHIA8_ROOT_DIR=${PYTHIA8_ROOT_DIR} HEPMC_DIR=${PREFIX}

cd $WORKDIR
cd models/smash
mkdir build
cd build
cmake .. -DPythia_CONFIG_EXECUTABLE=$PREFIX/pythia8310/bin/pythia8-config -DCMAKE_INSTALL_PREFIX=$PREFIX
make -j8
make install

cd $WORKDIR/scripts
chmod 777 *
cd $WORKDIR
