Logging:
    default: INFO

General:
    Modus:         List
    Time_Step_Mode: Fixed
    Delta_Time:    1.0
    End_Time:      1000.0
    Randomseed:    -1
    Nevents:       100

Output:
    Output_Interval: 1000.0
    Particles:
        Format:          ["Oscar2013","HepMC_treeroot"]

Collision_Term:
    No_Collisions: True
    Force_Decays_At_End: True
    
Modi:
    List:
        # If the build directory is not located in the smash directory anymore,
        # the absolute path specified below will not work anymore.
        # You can alternatively pass the path directly from the command line
        # with the "-c" command:
        # ./smash -i <path to config file> -c 'Modi: { List: { File_Directory: <path to file that is read in> } }
        File_Directory: "../input/list"
        Filename: "particle_list_osc.dat"

